name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: alpine # Cambiado a una versión específica de Alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers # Añadida acción para caché de capas Docker
        uses: actions/cache@v2
        with:
          path: /root/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker-compose build
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose push
